# Change these first
owner: fovir-github # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Home Page
    url: https://www.fovir.fyi/
    type: globalping
  - name: Wakapi
    url: https://wakapi.fovir.fyi/
    type: globalping
  - name: Music
    url: https://music.fovir.fyi/
    type: globalping
  - name: Book
    url: https://book.fovir.fyi/
    type: globalping
  - name: OpenList
    url: https://list.fovir.fyi/
    type: globalping
  - name: RSS
    url: https://rss.fovir.fyi/
    type: globalping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fovir.fyi
  # baseUrl: /your-repo-name
  logoUrl: https://img.fovir.fyi/fovir.png
  favicon: https://img.fovir.fyi/fovir.png
  name: Status | Fovir Sites
  introTitle: "Status Page of `*.fovir.fyi`"
  introMessage: This page monitors my websites.
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
